language: node_js

os: linux

cache: false

node_js:
  - "8"
  - "10"
  - "node"

script:
  - echo "Running tests against $(node -v) ..."
  - npm run build
  - npm run lint
  - npm run test-cov
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls

jobs:
  include:
    - stage: github pages
      node_js: "10"
      script: echo "Publish docs to github pages ..."
      before_deploy:
        - npm run docs
      deploy:
        provider: pages
        token: $GITHUB_TOKEN
        keep_history: false
        local_dir: doc
        skip_cleanup: true
        on:
          branch: master

    - stage: github release
      node_js: "10"
      script: echo "Deploying to github release ..."
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        on:
          tags: true

    - stage: npm release
      node_js: "10"
      script:
        - echo "Deploying to npm ..."
        - yarn build
      deploy:
        provider: npm
        email: zrp1994@gmail.com
        api_token: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
