name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['10', '12', '14']
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache npm dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-cache
        restore-keys: npm-cache
    - name: Install dependencies
      run: npm install
    - name: Compile source code
      run: npm run build
    - name: Run tests
      run: npm run test
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Cache npm dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-cache
        restore-keys: npm-cache
    - name: Install dependencies
      run: npm install
    - name: Compile source code
      run: npm run build
    - name: Run coverage tests
      run: npm run test-cov
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
